name: Deploy DEV to FTP

on:
  push:
    branches:
      - dev  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Zip the folder
        run: zip -r archive.zip . -x "./.git/*" "./.github/*"

      - name: Defining environment variables
        env:
          INTERFACE_EDITOR_DOMAIN: json.ms
          INTERFACE_EDITOR_URL: https://json.ms
          ACCESS_CONTROL_ALLOW_ORIGIN: https://json.ms
          PUBLIC_FILE_PATH: https://json.ms/files/
          GOOGLE_OAUTH_CLIENT_ID: 637442439591-qrrpb3v9d3n5m8b8gheorfa1fbi5o6qc.apps.googleusercontent.com
          GOOGLE_OAUTH_CALLBACK_URL: https://server.json.ms/google/callback
          JSONMS_CYPHER_KEY: ${{ secrets.JSONMS_CYPHER_KEY }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_DBNAME: ${{ secrets.DATABASE_DEV_DBNAME }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
        run: |
          echo "Value of INTERFACE_EDITOR_DOMAIN is $INTERFACE_EDITOR_DOMAIN"
          echo "Value of INTERFACE_EDITOR_URL is $INTERFACE_EDITOR_URL"
          echo "Value of ACCESS_CONTROL_ALLOW_ORIGIN is $ACCESS_CONTROL_ALLOW_ORIGIN"
          echo "Value of PUBLIC_FILE_PATH is $PUBLIC_FILE_PATH"
          echo "Value of GOOGLE_OAUTH_CLIENT_ID is $GOOGLE_OAUTH_CLIENT_ID"
          echo "Value of GOOGLE_OAUTH_CALLBACK_URL is $GOOGLE_OAUTH_CALLBACK_URL"

      - name: Deploy via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          source: "archive.zip"
          target: ${{ secrets.FTP_SERVER_DEV_PATH }}

      - name: SSH into server and unzip
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          script: |
            cd ${{ secrets.FTP_SERVER_DEV_PATH }}
            unzip -o archive.zip -d .
